[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
godot = "0.2.4"
rand = "0.9.0"
strum = { version = "0.27.1", features = ["derive"] }


[lib]
crate-type = ["cdylib"]  # Compile this crate to a dynamic C library.
